spring.cloud.discovery.enabled=true

spring.datasource.username=root
spring.datasource.password=Winners@05
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.cloud.config.enabled=true
spring.cloud.config.import-check.enabled=true

eureka.client.enabled=true
eureka.client.service-url.defaultZone=${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
management.endpoints.web.exposure.include=*

spring.datasource.hikari.initializationFailTimeout=0
spring.datasource.hikari.connectionTimeout=30000