spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          url-expression: "'lb://'+serviceId.toLowerCase()"
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
        - id: doctor-service
          uri: lb://doctor-service
          predicates:
            - Path=/api/doctors/**
          filters:
            - StripPrefix=1
        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/api/appointments/**
          filters:
            - StripPrefix=1

server:
  port: 8888

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://emsi-cabinet-discovery-service:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:localhost}

# Activer tous les endpoints actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always